### ISSUE TITLE
login in enhydris_api, a different approach with session

### ISSUE THREAD

**Issue by kickapoo** [openmeteo/pthelma#21]
Comments in `pthelma.enhydris_api.login` states a problem with headers between Python 2.7 and Python 3. 
How about using  `requests.session` ? (the following code is tested to python 2.7 and 3.4). 

``` python
import requests

# User login
data_login = {'action':"/accounts/login/", 'username':USERNAME, 'password':PASSWORD}

# Create session
session = requests.session()
r = session.get('http://openmeteo.org/accounts/login/', data=data_login)

#Fetch example station
station_example = requests.get('https://openmeteo.org/api/Station/1334/', cookies=r.cookies)
station_example.json()
```

`r.cookies` provides a `requests.cookies.RequestsCookieJar` class for reuse in protected pages.

**Comment by aptiko** [comment]
The comment in the code describes a problem in post requests. Your code seems to be doing only get requests.

**Comment by kickapoo** [comment]
Indeed, 
Please indicated a protected page to check something like 

```python 
from request import session

with session() as c:
    c.post('http://openmeteo.org/accounts/login/', data=data_login)
    r= c.get('https://openmeteo.org/<protected_page>)
    print r.headers()
```

**Comment by aptiko** [comment]
There should be everything you need in the unit tests (`test_enhydris_api.py`).
